name: 'release'
on:
  workflow_dispatch:
    inputs:
      is-snapshot:
        type: boolean
        description: Publish snapshot version
        default: false
      is-hotfix:
        type: boolean
        description: Publish hotfix version
        default: false
env:
  NPM_CONFIG_GITHUB_REGISTRY: https://npm.pkg.github.com
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          registry-url: ${{env.NPM_CONFIG_GITHUB_REGISTRY}}
          scope: '@synix'

      - name: Set env
        run: |
          echo "CI_PIPELINE_ID=${{ github.run_id }}${{ github.run_attempt }}" >> $GITHUB_ENV
          echo "IS_SNAPSHOT=${{ github.event.inputs.is-snapshot }}" >> $GITHUB_ENV
          echo "IS_HOTFIX=${{ github.event.inputs.is-hotfix }}" >> $GITHUB_ENV

      - run: npm install

      - name: Run test
        run: npm run test

      - name: Build package
        run: npm run build:ts

      - name: Authenticate with Github NPM
        run: |
          echo "@synix:registry=$NPM_CONFIG_GITHUB_REGISTRY" >> .npmrc
          echo "//npm.pkg.github.com/:_authToken=${{ secrets.GITHUB_TOKEN }}" >> .npmrc
          echo "always-auth=true" >> .npmrc

      - name: Prepare for publish
        run: npm run pkg-release

      - name: Publish to Github Packages
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}

      - name: Archive npm failure logs
        uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: npm-logs
          path: ~/.npm/_logs    